"""Add discord_user_id to User model and make password nullable

Revision ID: 08d1ca6d47f6
Revises: 0f6591c02677
Create Date: 2025-06-29 02:32:04.832351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d1ca6d47f6'
down_revision = '0f6591c02677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discord_user_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint("uq_user_discord_user_id", ['discord_user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_discord_user_id", type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('discord_user_id')

    # ### end Alembic commands ###
