"""Enhance Ticket model again

Revision ID: ce0113e58dc8
Revises: 210ac93c3de7
Create Date: 2025-06-29 03:38:03.745915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0113e58dc8'
down_revision = '210ac93c3de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        # Added server_default for existing rows as status is not nullable.
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='unpaid'))
        batch_op.add_column(sa.Column('dispute_reason', sa.Text(), nullable=True))
        # Default for dispute_status in model is 'none', nullable=True is fine for existing rows.
        batch_op.add_column(sa.Column('dispute_status', sa.String(length=50), nullable=True, server_default='none'))
        # Default for updated_at in model is datetime.utcnow, onupdate=datetime.utcnow.
        # nullable=True is fine for existing rows. onupdate is a DB trigger, not explicitly set here for SQLite usually.
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('paid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        # Original 'paid' column had default=False
        batch_op.add_column(sa.Column('paid', sa.BOOLEAN(), nullable=True, server_default=sa.false()))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('dispute_status')
        batch_op.drop_column('dispute_reason')
        batch_op.drop_column('status')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
